name: Release

on: release

jobs:
  artifactvalidator:
    name: artifactvalidator
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Setup go 1.13
        uses: actions/setup-go@v1
        with: {go-version: '1.13'}
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        run: |
          go build .
          zip -r ${{ matrix.os }}.zip artifactvalidator*
        working-directory: ./cmd/artifactvalidator
        shell: bash
        if: matrix.os != 'windows-latest'

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
